### ISSUE TITLE
1.0.29版本集成后，在部分手机打开应用报错，截图如下

### ISSUE THREAD

**Issue by HoneyWorld** [2tu/msa#10]
![1671443400358](https://user-images.githubusercontent.com/13584168/208397430-518e7ba4-387c-4394-a8e1-b8c37da4824a.png)

**Comment by 2tu** [comment]
Thanks for being in touch.I will respond as soon as possible!

**Comment by HoneyWorld** [comment]
接到反馈的有小米手机这样的问题，补充截图
![image](https://user-images.githubusercontent.com/13584168/208798277-fe156906-fb7e-461c-bee6-03a007297fe8.png)
![image](https://user-images.githubusercontent.com/13584168/208798329-e66a7152-e6c8-491b-8508-94453131a798.png)

**Comment by HoneyWorld** [comment]
设备是小米12pro，mui13，发现了一篇文章与这个有关，https://www.yimenapp.com/kb-yimen/12719/，希望能快点给出回复

**Comment by 2tu** [comment]
Thanks for being in touch.I will respond as soon as possible!
