### ISSUE TITLE
pixel 和 索尼手机可以获取到OAID吗？

### ISSUE THREAD

**Issue by ffdsss** [2tu/msa#11]
pixel 和 索尼手机可以获取到OAID吗？

**Comment by 2tu** [comment]
支持厂商列表如下
版本：2.1.0
发布日期： 2023年2月14日
![image](https://user-images.githubusercontent.com/14172964/220877046-2f74e088-abe4-40d5-ab84-2f72f1f3b02d.png)

**Comment by ffdsss** [comment]
国外的手机10版本以上有没有类似的 id 值

**Comment by 2tu** [comment]
> 国外的手机10版本以上有没有类似的 id 值

海外只有使用正规的广告ID或实例ID了
参见   https://developer.android.google.cn/training/articles/user-data-ids?hl=zh-cn

**Comment by ffdsss** [comment]
ok
