### ISSUE TITLE
您好，1.0.26更新了，辛苦更新一下

### ISSUE THREAD

**Issue by HuYueling** [2tu/msa#4]
2021年7月2日 version 1.0.26

      1.增加支持荣耀、realme、酷赛、Cool OS；

      2.增加包名校验机制；

      3.更新加固方案；

      4.增加补充设备标识符开关接口。

**Comment by liyujiang-gzu** [comment]
> 2021年7月2日 version 1.0.26
> 
> ```
>   1.增加支持荣耀、realme、酷赛、Cool OS；
> 
>   2.增加包名校验机制；
> 
>   3.更新加固方案；
> 
>   4.增加补充设备标识符开关接口。
> ```

需要提供企业信息注册账号的才能下载
