### ISSUE TITLE
您好，1.0.29更新了，辛苦更新一下

### ISSUE THREAD

**Issue by liyujiang-gzu** [2tu/msa#7]
2021年9月30日 version 1.0.29

      1. 增加支持步步高（小天才）接口

      2. 捕获第三方SDK接口方法实现报错，修复崩溃问题

      3. 更新加固方案，减小加固包体积

      4. 修复已知问题

**Comment by 2tu** [comment]
> ```
>   2021年9月30日 version 1.0.29
> 
>   1. 增加支持步步高（小天才）接口
> 
>   2. 捕获第三方SDK接口方法实现报错，修复崩溃问题
> 
>   3. 更新加固方案，减小加固包体积
> 
>   4. 修复已知问题
> ```

更新了
