### ISSUE TITLE
您好，1.0.30更新了，辛苦更新一下

### ISSUE THREAD

**Issue by liyujiang-gzu** [2tu/msa#8]
```
  2021年10月21日 version 1.0.30

      1. 更新魅族接口

      2. 更新加固方案，固定加固包中so文件名称

      3. 修复已知问题
```

**Comment by 2tu** [comment]
> ```
>   2021年10月21日 version 1.0.30
> 
>       1. 更新魅族接口
> 
>       2. 更新加固方案，固定加固包中so文件名称
> 
>       3. 修复已知问题
> ```

更新了
